### ISSUE TITLE
500 Error - https://foaaslack.herokuapp.com/fuckoff

### ISSUE THREAD

**Issue by mujahidhemani** [revmischa/foaas-slack#1]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by revmischa** [comment]
It expects some webhook arguments to be passed in. It could have a friendlier error message I guess.

**Comment by mujahidhemani** [comment]
I misunderstood how to setup the integration and didn't realize it's all done through slack whoops
